import { HealthCenter } from './types'

export const healthCentersSudan: HealthCenter[] = [
  {
    id: '1',
    name: 'Khartoum Central Health Center',
    nameAr: 'مركز الخرطوم الصحي المركزي',
    address: 'Khartoum, Sudan',
    addressAr: 'الخرطوم، السودان',
    phone: '+249-1-12345678',
    vaccinesAvailable: [
      'BCG',
      'Polio',
      'Pentavalent',
      'Measles',
      'Yellow Fever',
      'PCV',
      'Rotavirus',
    ],
    isOpen: true,
    status: 'متوفر',
    latitude: 15.5,
    longitude: 32.5,
  },
  {
    id: '2',
    name: 'Omdurman Vaccination Clinic',
    nameAr: 'عيادة أم درمان للتطعيمات',
    address: 'Omdurman, Sudan',
    addressAr: 'أم درمان، السودان',
    phone: '+249-1-87654321',
    vaccinesAvailable: [
      'BCG',
      'Polio',
      'Pentavalent',
      'Measles',
      'PCV',
      'Rotavirus',
    ],
    isOpen: true,
    status: 'متوفر',
    latitude: 15.6,
    longitude: 32.3,
  },
  {
    id: '3',
    name: 'Bahri Child Health Center',
    nameAr: 'مركز بحري لصحة الطفل',
    address: 'Bahri, Sudan',
    addressAr: 'بحري، السودان',
    phone: '+249-1-11111111',
    vaccinesAvailable: [
      'BCG',
      'Polio',
      'Pentavalent',
      'Measles',
      'Yellow Fever',
      'PCV',
    ],
    isOpen: false,
    status: 'غير متوفر حالياً',
    latitude: 15.7,
    longitude: 32.6,
  },
  {
    id: '4',
    name: 'Sudan Medical Center',
    nameAr: 'مركز السودان الطبي',
    address: 'Khartoum East, Sudan',
    addressAr: 'شرق الخرطوم، السودان',
    phone: '+249-1-22222222',
    vaccinesAvailable: [
      'BCG',
      'Polio',
      'Pentavalent',
      'Measles',
      'Yellow Fever',
      'PCV',
      'Rotavirus',
    ],
    isOpen: true,
    status: 'متوفر',
    latitude: 15.4,
    longitude: 32.7,
  },
  {
    id: '5',
    name: 'Al-Nile Health Clinic',
    nameAr: 'عيادة النيل الصحية',
    address: 'River Nile Area, Sudan',
    addressAr: 'منطقة النيل، السودان',
    phone: '+249-1-33333333',
    vaccinesAvailable: ['BCG', 'Polio', 'Pentavalent', 'Measles'],
    isOpen: true,
    status: 'متوفر',
    latitude: 15.65,
    longitude: 32.4,
  },
]
